import { describe, it, expect, vi } from 'vitest';
import { renderHook, act } from '@testing-library/react';
import { QuizProvider, useQuiz } from '../state/QuizProvider.js';

describe('QuizProvider', () => {
    it('should initialize with default state', () => {
        const wrapper = ({ children }) => <QuizProvider>{children}</QuizProvider>;
        const { result } = renderHook(() => useQuiz(), { wrapper });
        
        expect(result.current.state.quizSet).toBeNull();
        expect(result.current.state.selectedPromptTypes).toEqual(['location', 'name', 'flag']);
        expect(result.current.state.currentPrompt).toBeNull();
    });

    it('should update quizSet when setQuizSet is called', () => {
        const wrapper = ({ children }) => <QuizProvider>{children}</QuizProvider>;
        const { result } = renderHook(() => useQuiz(), { wrapper });
        
        act(() => {
            result.current.setQuizSet('Europe');
        });
        
        expect(result.current.state.quizSet).toBe('Europe');
    });

    it('should start quiz with valid config', () => {
        const wrapper = ({ children }) => <QuizProvider>{children}</QuizProvider>;
        const { result } = renderHook(() => useQuiz(), { wrapper });
        
        act(() => {
            result.current.setQuizSet('Test Set');
            result.current.setSelectedPromptTypes(['name', 'flag']);
        });
        
        act(() => {
            result.current.startQuiz();
        });
        
        expect(result.current.state.quizCountryData.length).toBeGreaterThan(0);
        // Prompt should be generated by useEffect
    });
});