import React from 'react';
import { describe, it, expect, vi } from 'vitest';
import { renderHook, act } from '@testing-library/react';
import { QuizProvider } from '../state/quizProvider.jsx';
import { useQuiz } from '../hooks/useQuiz.js';
import { useQuizActions } from '../hooks/useQuizActions.js';

describe('QuizProvider', () => {
    it('should initialize with default state', () => {
        const wrapper = ({ children }) => <QuizProvider>{children}</QuizProvider>;
        const { result } = renderHook(() => useQuiz(), { wrapper });
        
        expect(result.current.state.quizSet).toBeNull();
        expect(result.current.state.selectedPromptTypes).toEqual(['location', 'name', 'flag']);
        expect(result.current.state.currentPrompt).toBeNull();
    });

    it('should update quizSet when setQuizSet is called', () => {
        const wrapper = ({ children }) => <QuizProvider>{children}</QuizProvider>;
        const { result } = renderHook(() => {
            const quiz = useQuiz();
            const actions = useQuizActions();
            return { quiz, actions };
        }, { wrapper });
        
        act(() => {
            result.current.actions.setQuizSet('Europe');
        });
        
        expect(result.current.quiz.state.quizSet).toBe('Europe');
    });

    it('should start quiz with valid config', () => {
        const wrapper = ({ children }) => <QuizProvider>{children}</QuizProvider>;
        const { result } = renderHook(() => {
            const quiz = useQuiz();
            const actions = useQuizActions();
            return { quiz, actions };
        }, { wrapper });
        
        act(() => {
            result.current.actions.setQuizSet('Europe');
            result.current.actions.setSelectedPromptTypes(['name', 'flag']);
        });
        
        act(() => {
            result.current.actions.startQuiz();
        });
        
        expect(result.current.quiz.state.quizCountryData.length).toBeGreaterThan(0);
        // Prompt should be generated by useEffect
    });
});